plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/changelog"
- "@semantic-release/git"
- "@semantic-release/exec":
    prepareCmd: "docker build -t christiansiegel/semantic-release-test ."
- "semantic-release-docker":
    name: "christiansiegel/semantic-release-test"
- "@semantic-release/github"
