branch: master
preset: conventionalcommits # https://www.conventionalcommits.org/
tagFormat: "v${version}"
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- - "@semantic-release/changelog"
  - changelogFile: "CHANGELOG.md"
    changelogTitle: Changelog
- - "@google/semantic-release-replace-plugin"
  - replacements:
    - files: [ "setup.py "]
      from: "version=\".*\""
      to: "version=\"${nextRelease.version}\""
      countMatches: true
      results:
        - file: "setup.py"
          hasChanged: true
          numMatches: 1
          numReplacements: 1
- - "@semantic-release/git"
  - assets:
    - "setup.py"
    - "CHANGELOG.md"
- - "@semantic-release/exec":
  - prepareCmd: "docker build -t christiansiegel/semantic-release-test ."
- - "semantic-release-docker":
  - name: "christiansiegel/semantic-release-test"
- "@semantic-release/github"
