branch: master
preset: conventionalcommits # https://www.conventionalcommits.org/
tagFormat: "v${version}"
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- - "@google/semantic-release-replace-plugin"
  - replacements:
    - files: [ "setup.py "]
      from: "version=\"dev\""
      to: "version=\"${nextRelease.version}\""
      countMatches: true
      results:
        - file: "setup.py"
          hasChanged: true
          numMatches: 1
          numReplacements: 1
- - "@semantic-release/exec"
  - verifyCmd: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    prepareCmd: docker build -t $IMAGE_NAME:latest .
    publishCmd: |
      docker push $IMAGE_NAME:latest
      docker tag $IMAGE_NAME:latest $IMAGE_NAME:${nextRelease.version}
      docker push $IMAGE_NAME:${nextRelease.version}
- "@semantic-release/github"
